---
title: "Projet Dune"
output:
  html_document:
    df_print: paged
---

# Initialisation de l'environnement
```{r}
rm(list=ls())
```
# Chargement des bibliothèques
```{r}
# install.packages("tidytext")
library("tidytext")
# install.packages("tidyverse")
library("tidyverse")
# install.packages("igraph")
library("igraph")
# install.packages("reshape2")
library("reshape2")
# install.packages("wordcloud")
library("wordcloud")
# install.packages("ggraph")
library("ggraph")
# install.packages("widyr")
library("widyr")
```


# Chargement des données
```{r}
data <- readLines("Frank Herbert - Dune.txt")
```

```{r}
data_split <- data_frame(line = 1:length(data), text = data)
```

```{r}
#data_split[data_split$line == "= = = = = =",]
data_split$chapitre <- cumsum(as.integer(data_split$text=="= = = = = ="))+1
dim(data_split)
```

## Transformation du jeu de données pour faire apparaître le numéro des chapitres
```{r}
data_chapter <- data_split[-which(data_split$text=="= = = = = ="),]
sep_partie <- as.integer(names(which(table(data_chapter$chapitre)==4)))
data_chapter$partie <- cumsum(as.integer(data_chapter$chapitre %in% sep_partie))+1
data_chapter <- data_chapter[-which(data_chapter$chapitre %in% sep_partie),]
# data_clean : 46 facteurs
# data_brut : 51 facteurs
data_chapter$chapitre = as.factor(data_chapter$chapitre)
levels(data_chapter$chapitre) = as.factor(1:51)
data_chapter$partie = as.factor(data_chapter$partie)
levels(data_chapter$partie) = as.factor(1:3)
table(data_chapter$chapitre)
table(data_chapter$partie)
```


```{r}
df_initial <- data_frame(line = 1:length(data), text = data)
```

# Tutoriel tidy text
```{r}
df <- df_initial %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words)
```

```{r}
df %>%
  count(word, sort = TRUE) %>%
  filter(n > 300) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip()
```

```{r}
df %>%
  count(word, sort = TRUE)
```


```{r}
df %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE) %>%
  acast(word ~ sentiment, value.var = "n", fill = 0) %>%
  comparison.cloud(colors = c("gray10", "gray50"),
                   max.words = 500, scale=c(4,.25))
```

# TF-IDF
```{r}
freq_by_rank <- df_initial %>%
  unnest_tokens(word, text) %>%
  count(word, sort = TRUE) %>%
  ungroup() %>%
  mutate(rank = row_number(),
         total = sum(n),
         'term frequency' = n / total)

dim(freq_by_rank)
head(freq_by_rank)
```



```{r}
rank_subset <- freq_by_rank %>%
  filter(rank < 500,
         rank > 10)

lm(log10(`term frequency`) ~ log10(rank), data = rank_subset)
```


```{r}
freq_by_rank %>%
  ggplot(aes(rank, `term frequency`)) + 
  geom_abline(intercept = -0.837, slope = -1.0192, color = "gray50", linetype = 2) +
  geom_line(size = 1.1, alpha = 0.8, show.legend = FALSE) + 
  scale_x_log10() +
  scale_y_log10()
```


```{r}
freq_by_rank %>%
  select(-total) %>%
  arrange(desc(`term frequency`))
```

# n-gram
```{r}
bigrams2 <- df_initial %>%
  unnest_tokens(bigram, text, token = "ngrams", n = 2) %>%
  separate(bigram, c("word1", "word2"), sep = " ") %>%
  filter(!word1 %in% stop_words$word) %>%
  filter(!word2 %in% stop_words$word) %>%
  count(word1, word2, sort = TRUE)

bigrams3 <- df_initial %>%
  unnest_tokens(bigram, text, token = "ngrams", n = 3) %>%
  separate(bigram, c("word1", "word2", "word3"), sep = " ") %>%
  filter(!word1 %in% stop_words$word) %>%
  filter(!word2 %in% stop_words$word) %>%
  filter(!word3 %in% stop_words$word) %>%
  count(word1, word2, word3, sort = TRUE)

bigrams4 <- df_initial %>%
  unnest_tokens(bigram, text, token = "ngrams", n = 4) %>%
  separate(bigram, c("word1", "word2", "word3", "word4"), sep = " ") %>%
  filter(!word1 %in% stop_words$word) %>%
  filter(!word2 %in% stop_words$word) %>%
  filter(!word3 %in% stop_words$word) %>%
  filter(!word4 %in% stop_words$word) %>%
  count(word1, word2, word3, word4, sort = TRUE)

bigrams5 <- df_initial %>%
  unnest_tokens(bigram, text, token = "ngrams", n = 5) %>%
  separate(bigram, c("word1", "word2", "word3", "word4", "word5"), sep = " ") %>%
  filter(!word1 %in% stop_words$word) %>%
  filter(!word2 %in% stop_words$word) %>%
  filter(!word3 %in% stop_words$word) %>%
  filter(!word4 %in% stop_words$word) %>%
  filter(!word5 %in% stop_words$word) %>%
  count(word1, word2, word3, word4, word5, sort = TRUE)
```

```{r}
bigrams2_filtered <- bigrams2 %>%
  unite(bigram, word1, word2, sep = " ")

bigrams3_filtered <- bigrams3 %>%
  unite(bigram, word1, word2, word3, sep = " ")

bigrams4_filtered <- bigrams4 %>%
  unite(bigram, word1, word2, word3, word4, sep = " ")

bigrams5_filtered <- bigrams5 %>%
  unite(bigram, word1, word2, word3, word4, word5, sep = " ")
```

```{r}
bigrams2_filtered
bigrams3_filtered
bigrams4_filtered
bigrams5_filtered
```


```{r}
bigram_graph <- bigrams2 %>%
  filter(n > 10) %>%
  graph_from_data_frame()

ggraph(bigram_graph, layout = "fr") +
  geom_edge_link() +
  geom_node_point() +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1)
```


```{r}
bigram_graph <- bigrams2 %>%
  filter(n > 20) %>%
  graph_from_data_frame()

a <- grid::arrow(type = "closed", length = unit(.15, "inches"))

ggraph(bigram_graph, layout = "fr") +
  geom_edge_link(aes(edge_alpha = n), show.legend = FALSE,
                 arrow = a, end_cap = circle(.07, 'inches')) +
  geom_node_point(color = "lightblue", size = 5) +
  geom_node_text(aes(label = name), vjust = 1, hjust = 1) +
  theme_void()
```

```{r}
section_words <- df_initial %>%
  mutate(section = row_number() %/% 10) %>%
  filter(section > 0) %>%
  unnest_tokens(word, text) %>%
  filter(!word %in% stop_words$word)
```

```{r}
word_pairs <- section_words %>%
  pairwise_count(word, section, sort = TRUE)
word_pairs
```

```{r}
word_cors <- section_words %>%
  group_by(word) %>%
  filter(n() >= 50) %>%
  pairwise_cor(word, section, sort = TRUE)

dim(word_cors)
```

```{r}
word_cors %>%
  filter(correlation > .20) %>%
  graph_from_data_frame() %>%
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = correlation), show.legend = FALSE) +
  geom_node_point(color = "lightblue", size = 5) +
  geom_node_text(aes(label = name), repel = TRUE) +
  theme_void()
```

