---
title: "Web scraping"
author: "Jade Hoang"
date: "30/11/2018"
output: html_document
---

```{r,echo = F}
library(tidyverse)
library(rvest)
library(stringr) 
# install.packages("rebus")
library(rebus)
library(lubridate)
```

```{r}
url <-'https://en.wikipedia.org/wiki/Dune_(novel)#Characters'
# url <- "https://en.wikipedia.org/wiki/List_of_Dune_characters#Frank_Herbert_works"

page <- read_html(url)
```

## Scraping à partir de Wiki Dune(Novel)
```{r}
group_data <- html_nodes(page,'dt') %>% html_text()
message("Nom des groupes de personnages:")
group_data
nom_perso <- html_nodes(page,'dl:nth-child(30) dt , dl:nth-child(26) dt , dl:nth-child(24) dt , h2+ dl dt , dl:nth-child(28) dt , li') %>% html_text()
nom_perso <- nom_perso[-c(1:31,65:length(nom_perso))]
message("Nom des personnages:")
nom_perso
nom_perso <- gsub("\\\"|[.]","",nom_perso)
nom_perso
```

## Scraping à partir de Wiki Liste de personnage
```{r}
# group_data <- html_nodes(page,"#Miscellaneous , #Fremen , #Honored_Matres , #Spacing_Guild , #Bene_Tleilax , #Bene_Gesserit , #House_Harkonnen , #House_Atreides") %>% html_text()
# message("Nom des groupes de personnages:")
# group_data
# 
# nom_perso <- html_nodes(page,'.mw-headline , #Miscellaneous , #Fremen , #Honored_Matres , #Spacing_Guild , #Bene_Tleilax , #Bene_Gesserit , #Imperial_House_Corrino , #House_Harkonnen ,#House_Atreides , li') %>% html_text()
# nom_perso <- nom_perso[-c(1:which(nom_perso == "Frank Herbert works"),
#                           which(nom_perso == "Brian Herbert and Kevin J. Anderson works"):length(nom_perso))]
# 
# nom_perso %>% str_replace_all(c("[.]" = "", ";" = ","))
# 
# message("Nom des personnages:")
# 
# nom_perso

```

#Regrouper les personnages par Maison ou organisation
```{r}
data_nom <- tibble(group = 1:length(nom_perso), nom = nom_perso)
data_nom$group <- cumsum(as.integer(data_nom$nom %in% group_data))
data_nom <- data_nom[-which(data_nom$nom %in% group_data),]


data_nom$group <- sapply(data_nom$group, function(x) {group_data[x]})
data_nom

```

#Les personnages de Dune
```{r}
personnage <- data_nom %>%
  separate(nom, "nom",",", extra = "drop" )

personnage$nom <- gsub("[[:punct:]]"," ",tolower(personnage$nom))
personnage <- as.data.frame(personnage, stringAsFactors = FALSE)
personnage$id <- 0:(nrow(personnage) - 1)
personnage
```

#Séparer les noms par différents noms utilisés dans le livre
```{r}
dict_perso <- cbind(select(personnage,-id), nom_dup = personnage$nom) %>%
  separate(nom_dup,c("nom1","nom2","nom3","nom4","nom5"), " ",extra = "drop")

dict_perso
```

#enlever les noms qui ne conviennent pas
```{r}
dict_perso[dict_perso == "atreides" | 
             dict_perso  == "harkonnen" |
             dict_perso  == "tuek" |
             dict_perso  == "fenring" |
             dict_perso == "the" | 
             dict_perso == "de" |
             dict_perso == "princess"|
             dict_perso == "lady" |
             dict_perso == "fremen"]<- NA

dict_perso$nom1[which(dict_perso$nom2== "margot")] <- "lady fenring"

dict_perso
```



